package app.kotlin.snapnote.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(color = 0xFF815512)
val onPrimaryLight = Color(color = 0xFFFFFFFF)
val primaryContainerLight = Color(color = 0xFFFFDDB7)
val onPrimaryContainerLight = Color(color = 0xFF2A1700)
val tertiaryContainerLight = Color(color = 0xFFBAF0B7)
val onTertiaryContainerLight = Color(color = 0xFF002106)
val errorLight = Color(color = 0xFF904A4A)
val surfaceLight = Color(color = 0xFFFFF8F4)
val onSurfaceLight = Color(color = 0xFF211A13)
val surfaceVariantLight = Color(color = 0xFFF0E0D0)
val onSurfaceVariantLight = Color(color = 0xFF504539)
val outlineLight = Color(color = 0xFF827568)
val outlineVariantLight = Color(color = 0xFFD4C4B5)
val surfaceContainerLowLight = Color(color = 0xFFFFF1E5)
val surfaceContainerLight = Color(color = 0xFFF9ECE0)
val surfaceContainerHighLight = Color(color = 0xFFF3E6DA)
val surfaceContainerHighestLight = Color(color = 0xFFEEE0D4)


val primaryDark = Color(color = 0xFFF7BB70)
val onPrimaryDark = Color(color = 0xFF462A00)
val primaryContainerDark = Color(color = 0xFF653E00)
val onPrimaryContainerDark = Color(color = 0xFFFFDDB7)
val tertiaryContainerDark = Color(color = 0xFF205026)
val onTertiaryContainerDark = Color(color = 0xFFBAF0B7)
val errorDark = Color(color = 0xFFFFB3B2)
val surfaceDark = Color(color = 0xFF18120C)
val onSurfaceDark = Color(color = 0xFFEEE0D4)
val surfaceVariantDark = Color(color = 0xFF504539)
val onSurfaceVariantDark = Color(color = 0xFFD4C4B5)
val outlineDark = Color(color = 0xFF9C8E80)
val outlineVariantDark = Color(color = 0xFF504539)
val surfaceContainerLowDark = Color(color = 0xFF211A13)
val surfaceContainerDark = Color(color = 0xFF251E17)
val surfaceContainerHighDark = Color(color = 0xFF302921)
val surfaceContainerHighestDark = Color(color = 0xFF3B332B)